name: "🚩 Pager duty Bug"
description: "Submit a bug that is impacting/blocking/limiting a Devtron functionality for an Enterprise."
title: "Bug: "
labels: ["bug","pager-duty"]
projects: ["Devtron Features Prioritization"]
assignees: ["prakarsh-dt","vikramdevtron","kripanshdevtron","vivek-devtron"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out our bug report form 🙏
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "📜 Description"
      description: "A clear and concise description of what the bug is."
      placeholder: "It bugs out when ..."
  - type: dropdown
    id: affected-areas
    attributes:
      label: "Affected areas"
      description: "What areas of Devtron are impacted by the issue?"
      options:
        - Devtron dashboard completely down
        - Login issues 
        - RBAC Issues 
        - CI 
        - CD 
        - App creation 
        - Deployment from Chart store 
        - Security features 
        - CI/CD Plugins 
        - Other CRITICAL functionality 
        - Other NON-CRITICAL functionality 
  - type: dropdown
    id: additional-affected-areas
    attributes:
      label: "Additional affected areas"
      description: "Are there any additional affected areas?"
      options:
        - Devtron dashboard completely down 
        - Login issues 
        - RBAC Issues 
        - CI 
        - CD 
        - App creation 
        - Deployment from Chart store 
        - Security features 
        - CI/CD Plugins 
        - Other CRITICAL functionality 
        - Other NON-CRITICAL functionality 
  - type: dropdown
    id: prod-environment
    attributes:
      label: "Prod/Non-prod environments?"
      description: "Is the issue affecting Prod environments?"
      options:
        - Prod 
        - Non-prod 
  - type: dropdown
    id: user-unblocked
    attributes:
      label: "Is User unblocked?"
      description: "Is the User unblocked?"
      options:
        - 'Yes'
        - 'No' 
  - type: dropdown
    id: user-unblocked-reason
    attributes:
      label: "How was the user un-blocked?"
      description: "If the user was unblocked. How was the user un-blocked?"
      options:
        - TEMPORARILY - By disabling a CRITICAL functionality 
        - TEMPORARILY - By disabling a NON-CRITICAL functionality 
        - TEMPORARILY - By doing some changes from the backend/DB 
        - PERMANENTLY - By giving a workaround (From outside Devtron) 
        - PERMANENTLY - By giving a workaround (Within Devtron) 
      
  - type: textarea
    id: kuberentes-version
    attributes:
      label: "☸ Kubernetes version"
      description: "What is your Kubernetes service and version?"
      placeholder: "EKS 1.23, KOps 1.22, AKS 1.21 etc."
    validations:
      required: true
