name: "🚩 Pager duty Bug"
description: "Submit a bug that is impacting/blocking/limiting a Devtron functionality for an Enterprise."
title: "Bug: "
labels: ["bug","pager-duty"]
projects: ["Devtron Features Prioritization"]
assignees: ["prakarsh-dt","vikramdevtron","kripanshdevtron","vivek-devtron"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out our bug report form 🙏
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "📜 Description"
      description: "A clear and concise description of what the bug is."
      placeholder: "It bugs out when ..."
  - type: dropdown
    id: affected-areas
    attributes:
      label: "Affected areas"
      description: "What areas of Devtron are impacted by the issue?"
      options:
        - Devtron dashboard completely down (100) Add URGENT
        - Login issues (50)
        - RBAC Issues (40)
        - CI (50)
        - CD (50)
        - App creation (30)
        - Deployment from Chart store (40)
        - Security features (50)
        - CI/CD Plugins (30)
        - Other CRITICAL functionality (30)
        - Other NON-CRITICAL functionality (20)
  - type: dropdown
    id: additional-affected-areas
    attributes:
      label: "Additional affected areas"
      description: "Are there any additional affected areas?"
      options:
        - Devtron dashboard completely down (100)
        - Login issues (50)
        - RBAC Issues (40)
        - CI (50)
        - CD (50)
        - App creation (30)
        - Deployment from Chart store (40)
        - Security features (50)
        - CI/CD Plugins (30)
        - Other CRITICAL functionality (30)
        - Other NON-CRITICAL functionality (20)
  - type: dropdown
    id: prod-environment
    attributes:
      label: "Prod/Non-prod environments?"
      description: "Is the issue affecting Prod environments?"
      options:
        - Prod (x2)
        - Non-prod (x1)
  - type: dropdown
    id: user-unblocked
    attributes:
      label: "Is User unblocked?"
      description: "Is the User unblocked?"
      options:
        - Yes (x1)
        - No (x2)
  - type: dropdown
    id: user-unblocked-reason
    attributes:
      label: "How was the user un-blocked?"
      description: "If the user was unblocked. How was the user un-blocked?"
      options:
        - TEMPORARILY - By disabling a CRITICAL functionality (x3) Add URGENT
        - TEMPORARILY - By disabling a NON-CRITICAL functionality (x1.2)
        - TEMPORARILY - By doing some changes from the backend/DB (x1)
        - PERMANENTLY - By giving a workaround (From outside Devtron) (x2)
        - PERMANENTLY - By giving a workaround (Within Devtron) (x1)
  - type: textarea
    id: impact
    validations:
      required: true
    attributes:
      label: "Impact on Enterprise"
      description: "Describe the kind of Impact this bug/issue has on an Enterprise."
      placeholder: "1. The users are unable to ..."
  - type: textarea
    id: steps-to-replicate
    validations:
      required: true
    attributes:
      label: "👟 Steps to replicate the Issue"
      description: "How do you trigger this bug? Please walk us through it step by step."
      placeholder: "1. When I ..."
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: "👍 Expected behavior"
      description: "What did you think would happen?"
      placeholder: "It should ..."
  - type: textarea
    id: actual-behavior
    validations:
      required: true
    attributes:
      label: "👎 Actual Behavior"
      description: "What did actually happen? Add screenshots, if applicable."
      placeholder: "It actually ..."
  - type: textarea
    id: kuberentes-version
    attributes:
      label: "☸ Kubernetes version"
      description: "What is your Kubernetes service and version?"
      placeholder: "EKS 1.23, KOps 1.22, AKS 1.21 etc."
    validations:
      required: true
