name: Issue Created
on:
  issues:
    types: [opened]

jobs:
  extract-issue-body:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if pager-duty template is used
        if: ${{ contains(github.event.issue.labels.*.name, 'pager-duty') && contains(github.event.issue.labels.*.name, 'bug') }}
        run: |
          echo "Issue was created using pager-duty template"
